import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/dist/client/script";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <title>Chanel Muir</title>
        <link rel="icon" href="/favicon.ico" />
        <Script 
          src="https://kit.fontawesome.com/cbfd9f18ad.js" 
          strategy="afterInteractive" 
        />
      </head>
      <body className="min-h-full flex flex-col bg-background">
        <Navbar />
        {children}</body>
    </html>
  );
}
